version: '3.8'

services:
  php-apache:
    build: .                           # Utilise le Dockerfile dans le répertoire courant
    ports:
      - "8080:80"                      # Redirige le port 80 du conteneur vers le port 8080 de la machine hôte
    volumes:
      - .:/var/www/html                # Monte le projet dans le conteneur pour permettre les modifications en direct
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "Pbourgeois62!"          
      MYSQL_DATABASE: web_dev_essentials    
      
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db                     # C'est ici que phpMyAdmin se connecte à MySQL
      MYSQL_ROOT_PASSWORD: "Pbourgeois62!"          
    ports:
      - "8081:80"                      # Accès à phpMyAdmin sur le port 8081
    networks:
      - app-network

networks:
  app-network:
    driver: bridge                     # Création d'un réseau de type bridge
